# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[package]
name = "hotshot-query-service"
version = "0.0.1"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"

[features]
default = []
testing = ["tempdir"]

[dependencies]
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
atomic_store = { git = "https://github.com/EspressoSystems/atomicstore.git", tag = "0.1.3" }
bincode = "1.3"
clap = { version = "4.0", features = ["derive", "env"] }
commit = { git = "https://github.com/EspressoSystems/commit.git", tag = "0.2.2" }
custom_debug = "0.5"
derive_more = "0.99"
futures = "0.3"
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "a154ee55a97ec9522fc043e9b7f6e47557f7956a", features = ["async-std-executor", "channel-async-std"] }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "a154ee55a97ec9522fc043e9b7f6e47557f7956a" }
hotshot-utils = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "a154ee55a97ec9522fc043e9b7f6e47557f7956a" }
itertools = "0.10"
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.7", features = ["backtraces"] }
spin_sleep = "1.1"
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco.git", tag = "v0.4.0" }
toml = "0.5"
tracing = "0.1"

# Dependencies enabled by feature "testing".
tempdir = { version = "0.3", optional = true }

[dev-dependencies]
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer.git", tag = "1.0.1" }
portpicker = "0.1"
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco.git", tag = "v0.4.0" }
tempdir = "0.3"
