# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[package]
name = "hotshot-query-service"
version = "0.0.1"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"

[features]
default = []
testing = []

[dependencies]
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
clap = { version = "4.0", features = ["derive", "env"] }
commit = { git = "https://github.com/EspressoSystems/commit.git", tag = "0.2.2" }
derive_more = "0.99"
hotshot = { git = "ssh://git@github.com/EspressoSystems/HotShot.git", rev = "835b55489f22ae9a16f4f4e41d4549b76a10f8ae", features = ["async-std-executor", "channel-async-std"] }
hotshot-types = { git = "ssh://git@github.com/EspressoSystems/HotShot.git", rev = "835b55489f22ae9a16f4f4e41d4549b76a10f8ae" }
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.7", features = ["backtraces"] }
tide-disco = { git = "ssh://git@github.com/EspressoSystems/tide-disco.git", rev = "a4ae3bf7feba517c305f03e21db4f1192dc45248" }
toml = "0.5"
